Make more UI text translatable
nyaruka/floweditor pull request #969
Opened 2021-03-03 20:57 UTC by rowanseymour

2021-03-03 21:02 UTC, rowanseymour commented on src/components/flow/actions/sendmsg/SendMsgForm.tsx
> +            'forms.all_destinations_description',
fixes 
<img width="688" alt="Captura de Pantalla 2021-03-03 a la(s) 14 27 10" src="https://user-images.githubusercontent.com/675558/109872062-e6144400-7c39-11eb-8e5f-951ed2e4f1cd.png">

2021-03-04 04:28 UTC, ericnewcomer requested changes

2021-03-04 04:28 UTC, ericnewcomer commented on src/components/flow/actions/localization/MsgLocalizationForm.tsx
> +        name: i18n.t('form.quick_replies', 'Quick Replies'),
I see `forms.*` and `form.*` I think this is supposed to be `forms.quick_replies`. I wouldn't be shocked if there are others.

2021-03-04 04:28 UTC, ericnewcomer commented on src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.tsx.snap
> +                placeholder="Select the flow to start"
👍

2021-03-04 14:15 UTC, merged